### ISSUE TITLE
How to add a horizontal list in the top preheader area.

### ISSUE THREAD

**Issue by paaljoachim** [wplemon/gridd#106]
Hey

The customer asked me to recreate something like the preheader here:
https://www.festkompaniet.no/

<img width="1100" alt="Screen Shot 2019-09-26 at 13 34 33" src="https://user-images.githubusercontent.com/5323259/65685503-65274500-e062-11e9-83fd-6f6c4a8936f6.png">

My guess would be to add 1 widget in the preheader and have the bullet points added next to each other in a horizontal way. I am experimenting with it here: https://fragmentsofawalk.com/ 
(I have not figured it out fully yet...gradually getting there.)

**Comment by paaljoachim** [comment]
I got it working with this CSS:

```
#text-13 {
	text-align: center;
}

#text-13 ul li:before {
        content: '\2713';
	display: inline-block;
        color: #fff;
	padding-right: 5px;
}

#text-13 ul li {
        padding: 20px 35px 0 0;
	text-align: center;
	display: inline;
	margin: auto;
	list-style: none;
	font-size: 1.2em;
}

#text-13 ul li:after {
	
}
```

**Comment by paaljoachim** [comment]
Ari we got to save the above example for the documentation.

**Comment by aristath** [comment]
These things won't be necessary in most cases...
Sure it can be done using a widget, however don't forget about reusable blocks! Users can simply create a reusable block, save it, and then add that in their grid. It's a lot simpler than adding custom-css, and you can achieve pretty much anything you want with that approach. If you can build it in Gutenberg, you can save it as a reusable block and presto - you've got a custom grid-part! 😉

**Comment by paaljoachim** [comment]
Adding a reusable block is a very good idea.
I am guessing I could use the list block and add the CSS I added earlier to get it looking as I need.
Do you have another suggestion?

**Comment by aristath** [comment]
It could just be a columns block with the links inside each column...
