### ISSUE TITLE
Theme Options -> Header

### ISSUE THREAD

**Issue by paaljoachim** [wplemon/gridd#108]
I noticed the purple Background Color overlaps the one vertical slider.
![Screen Shot 2019-09-29 at 22 48 16](https://user-images.githubusercontent.com/5323259/65839186-5c0cd100-e30b-11e9-9556-8955b94d3f48.png)

**Comment by aristath** [comment]
Thank you, marked as a bug. Will have to be fixed in Kirki 👍

**Comment by aristath** [comment]
Fixed in the dev branch
