### ISSUE TITLE
Default white button text seen as black on frontend

### ISSUE THREAD

**Issue by paaljoachim** [wplemon/gridd#111]
Adding a new button in Gutenberg the default text is seen as white text:

![Screen Shot 2019-09-30 at 07 49 23](https://user-images.githubusercontent.com/5323259/65852585-d878d180-e356-11e9-9cec-2a7444e7e3b3.png)

Going to the frontend:
Button text is black.

![Screen Shot 2019-09-30 at 07 50 02](https://user-images.githubusercontent.com/5323259/65852617-f6463680-e356-11e9-8ddf-5c192e60cfa3.png)

Customizer:

![Screen Shot 2019-09-30 at 07 51 38](https://user-images.githubusercontent.com/5323259/65852690-31486a00-e357-11e9-943f-dc0dce523c34.png)

https://fragmentsofawalk.com/

**Comment by paaljoachim** [comment]
What I end up doing is going to each button. Then selected the text color -> custom color of white (#fff).

**Comment by paaljoachim** [comment]
Checking another dev site to where I am developing the new site. It is behind a maintenance wall.
There I am at the moment (will update in a bit) using 1.1.17.
It has the same setup as the above. One difference is that the default white button text seen in the backend also is seen on the frontend.

**Comment by aristath** [comment]
Buttons are getting a big refactor in v1.2, so this will be solved in the next release 👍

**Comment by paaljoachim** [comment]
That is great!

**Comment by paaljoachim** [comment]
Yes, I noticed that the buttons text color shows up as it should in 1.2..:)
