### ISSUE TITLE
Customizer: How to close the select a color option in the Color palette

### ISSUE THREAD

**Issue by paaljoachim** [wplemon/gridd#119]
The color palette is very very nice!!

I can add colors and then change the color of each as I want, but I expect when I click outside the color palette select a color option that it closes. It is not doing so. I then look for ways to how to close it. I am not seeing any logical way to how to close the color palette.

<img width="392" alt="Screen Shot 2019-10-27 at 12 32 44" src="https://user-images.githubusercontent.com/5323259/67637972-537dcb00-f8b6-11e9-8982-101cb079796e.png">

**Comment by aristath** [comment]
Fixed

**Comment by paaljoachim** [comment]
One more thing.
customizer -> Layout Blocks -> Content.
Text Color. Not using Auto but going to Custom. Opening the color picker.

![Screen Shot 2019-10-30 at 16 31 34](https://user-images.githubusercontent.com/5323259/67896453-c4311b80-fb32-11e9-8c70-2f3035112f08.png)

The color picker screen seems stuck.

**Comment by paaljoachim** [comment]
I added the beta 2.0 plugin (without the plus plugin) to a new local dev site.

![Screen Shot 2019-10-30 at 16 53 31](https://user-images.githubusercontent.com/5323259/67897984-d3fe2f00-fb35-11e9-8f8f-87fa317061c7.png)

With the plus plugin it then adds the WCAG rating colors.

![Screen Shot 2019-10-30 at 16 56 18](https://user-images.githubusercontent.com/5323259/67898196-3ce5a700-fb36-11e9-937d-7433efb8b1dc.png)

I click Custom select a color and click outside of it, but nothing happens. The color area does not close.
