### ISSUE TITLE
Adding new widget areas.

### ISSUE THREAD

**Issue by paaljoachim** [wplemon/gridd#120]
(Edit: the below should have added to the Gridd-plus repo...:)

I added a bunch of new widget areas.

"Your theme has 7 other widget areas, but this particular page doesn’t display them.

You can navigate to other pages on your site while using the Customizer to view and edit the widgets displayed on those pages."

I began with the front page. Then went to the blog page. Then went to a post. I am still not able to view the new widget areas. They are not showing up in the widget area in the customizer.

<img width="1324" alt="Screen Shot 2019-10-27 at 12 41 31" src="https://user-images.githubusercontent.com/5323259/67638082-5fb65800-f8b7-11e9-8e32-d99bd3d82d28.png">

I believe there was somekind of "trick" to get them showing that I have forgotten about.

**Comment by paaljoachim** [comment]
Should there be a way for the user to decide where the widgets show up?
On the homepage, regular pages, posts, blog etc?

**Comment by paaljoachim** [comment]
O another thing the new widgets are not showing up here:
<img width="350" alt="Screen Shot 2019-10-27 at 12 55 54" src="https://user-images.githubusercontent.com/5323259/67638294-3991b780-f8b9-11e9-8e41-e726555471c6.png">

**Comment by aristath** [comment]
Fixed.

**Comment by paaljoachim** [comment]
I retested with beta 2.0 and plus plugin activated.

Theme Settings -> Global Settings.
Set number of custom widget areas to 5.
Clicked Publish. Did a hard refresh and reloaded the customizer.
Went to customizer -> widgets. Only Offcanvas Sidebar, and 3 footer widget areas are seen.

![Screen Shot 2019-10-30 at 17 05 55](https://user-images.githubusercontent.com/5323259/67898890-8f739300-fb37-11e9-916f-cab183a2ecaf.png)

Here is says 9 other widget areas.

Select frontpage, a page, the blog and a post to see if any additional widget areas show up. They do not.
