### ISSUE TITLE
Remove background color behind drop down arrow.

### ISSUE THREAD

**Issue by paaljoachim** [wplemon/gridd#124]
Today when hovering over a menu item that has a drop down it looks like this:

<img width="122" alt="Screen Shot 2019-10-27 at 14 18 53" src="https://user-images.githubusercontent.com/5323259/67639381-706dca80-f8c5-11e9-8703-4fefe81079f9.png">

Hovering over other menu items only the text color changes. No background color is seen.
It would be good to remove the background black as can be seen in the above example and instead have the arrow become red just like the shop menu link beside it.

**Comment by aristath** [comment]
Fixed
