### ISSUE TITLE
Using rem and em

### ISSUE THREAD

**Issue by paaljoachim** [wplemon/gridd#129]
I noticed in the site identity em is used but going to the navigation rem is used.
Should we stick to one or the other?

**Comment by aristath** [comment]
I'm still contemplating this one... 
The problem is that `em` is relative to its parent element, while `rem` refers to the root font-size. And though in most cases they are the same thing, there are scenarios where they differ.

**Comment by paaljoachim** [comment]
Ahh. Ok. I will close it, and if needed reopen at another time.

**Comment by aristath** [comment]
Reopened this one 'cause I encountered some visual inconsistencies. It needs to be consistent `em`.
