### ISSUE TITLE
Submenu arrows too far to the right of menu link.

### ISSUE THREAD

**Issue by paaljoachim** [wplemon/gridd#130]
Testing beta 2.0 with Plugin plugin activated.

![Screen Shot 2019-10-30 at 16 38 56](https://user-images.githubusercontent.com/5323259/67896953-ccd62180-fb33-11e9-99a8-e16aaf06c63d.png)

Notice the arrows are in the middle between two menu links. They do not seem associated with the link on the left side because of the distance of the left and right menu links. The arrows should be closer to the menu they belong to.

**Comment by aristath** [comment]
Good point. fixed.
