### ISSUE TITLE
New arrow icon for the drop down menu

### ISSUE THREAD

**Issue by paaljoachim** [wplemon/gridd#133]
Looking at the drop down icon today.

![Drop-down-arrow](https://user-images.githubusercontent.com/5323259/67907018-dddf5c80-fb4c-11e9-8df5-0a15b729172f.gif)

The arrow icon seems a bit big and could use a nice change to make it more subtile.

Here is an option:
https://a11y-guidelines.orange.com/web_EN/exemples/simple-menu/simple-menu.html

I will also look for other options.

Btw Having the current page underlined as well as clicking the drop down icon as well as hovering because a bit of a mess when three different things are all underlined as once. (I made a new issue for it.)

**Comment by paaljoachim** [comment]
From this culture house customer site: https://stabekkino.no/  

![Screen Shot 2019-10-31 at 12 37 49](https://user-images.githubusercontent.com/5323259/67967151-74f2f580-fbdb-11e9-9bde-f9190307d8b8.png)

**Comment by aristath** [comment]
Fixed. Now instead of a custom SVG it uses a unicode character `⌵`

**Comment by paaljoachim** [comment]
That is a very good way to do so. I have done so in the past myself. This also makes it very simple for the user to change to another unicode style. Please add some info to the FAQ.
