### ISSUE TITLE
Current menu link, click drop down arrow and hover another link - underlines

### ISSUE THREAD

**Issue by paaljoachim** [wplemon/gridd#134]
Go to a page listed in the menu.
See it underlined.

Click a drop down arrow.
See it underlined.

Hover over any other link.
See it underlined.

and all of this happens at the same time.

Notice the below.... 
The page test is the current page. 
The drop down icon has been clicked.
The last arrow is being hovered.

![Screen Shot 2019-10-31 at 12 41 19](https://user-images.githubusercontent.com/5323259/67967522-1c702800-fbdc-11e9-9a24-d6bde1a081b5.png)

Let's choose when a link is underlined. As today it is used in too many states at once.
What is best practice?
What is practical?
What looks good?

**Comment by aristath** [comment]
fixed
