### ISSUE TITLE
Should copyright information be located in the middle vertical position?

### ISSUE THREAD

**Issue by paaljoachim** [wplemon/gridd#141]
Here is the copyright information area:
![Screen Shot 2019-11-02 at 20 53 03](https://user-images.githubusercontent.com/5323259/68078730-e933c180-fdb2-11e9-90d3-d5d473e7280d.png)

Notice that the text is not in the middle vertical area.
Should the copyright information by default be located in the horizontal center AND vertical center?

**Comment by aristath** [comment]
Good catch. fixed.
