### ISSUE TITLE
Height control for the copyright area?

### ISSUE THREAD

**Issue by paaljoachim** [wplemon/gridd#142]
I am wondering if we should have a control for the height of the copyright area?
Defining the height directly inside the customizer. Of course this can be done through CSS.

![Screen Shot 2019-11-02 at 20 53 03](https://user-images.githubusercontent.com/5323259/68078763-4e87b280-fdb3-11e9-9734-18b27c0d14d1.png)

**Comment by aristath** [comment]
You can already define the height of that area from the Footer Grid setting 😉 
So the option is not part of the copyriaght-area options, it's part of the footer layout.
