### ISSUE TITLE
How to turn off Nav background color?

### ISSUE THREAD

**Issue by paaljoachim** [wplemon/gridd#143]
I went to the navigation and turned on a background color. I decided that I did not want a background color so I went to turn it off again.
![Screen Shot 2019-11-02 at 21 01 23](https://user-images.githubusercontent.com/5323259/68078815-a377f880-fdb4-11e9-89a0-ce6e644a3138.png)

How do I turn off the color? Or select a no-color option?

----

Another issue....

I clicked the various background color options and happen to notice that one of the menu nav links changed on some options.

Here is an example:

![Screen Shot 2019-11-02 at 21 08 13](https://user-images.githubusercontent.com/5323259/68078835-fb166400-fdb4-11e9-8fd4-9ec213a872f8.png)

**Comment by aristath** [comment]
> How do I turn off the color? Or select a no-color option?

There is no no-color option. You can simply select the color you previously had.

> I clicked the various background color options and happen to notice that one of the menu nav links changed on some options.

Should I assume that you have the "Override Header Parts Background" option enabled? If that is the case then color calculations can't properly run on the header sub-parts to select a properly readable color, and that seems to be the case here.
The color for nav-menu items is calculated for readability using the color selected in the navigation's background-color field.
You have selected black there, so naturally it uses light colors for the text-colors. However the actual background displayed on the preview pane is a light blue, so I assume that is the color you have selected for the global header and override background colors of individual grid-parts.
It's definitely a quirk, but I wouldn't categorize it as a _bug_... And it hasn't really changed in v2.0, that was always the case in previous versions too. The only thing that changed is the colorpickers there.
Ideally when you enable the "Override Header Parts Background", we would check the grid-parts assigned the header, find their background-color settings, hide them and silently change their value to correspond to the color selected in the main header-background-color control. That would however require further automation and extra queries that have not been implemented in v2.0. We can do it in v2.1 if the current implementation is confusing.
