### ISSUE TITLE
Customizer: Previewing Gridd 2.0.1

### ISSUE THREAD

**Issue by paaljoachim** [wplemon/gridd#145]
Hey Ari

I made a new local dev site where I started with Gridd 2.0.1. 

![Activating-Gridd-theme](https://user-images.githubusercontent.com/5323259/68142341-49cf1580-fefd-11e9-8e10-e0900726b12a.gif)

![Screen Shot 2019-11-04 at 12 13 32](https://user-images.githubusercontent.com/5323259/68142371-58b5c800-fefd-11e9-9b0e-d6096e7ac06d.png)

![Screen Shot 2019-11-04 at 12 13 48](https://user-images.githubusercontent.com/5323259/68142380-5d7a7c00-fefd-11e9-8023-c085444d55f7.png)

Plugin conflict with:
https://wordpress.org/plugins/filebird/

I sent a chat message here: https://ninjateam.org/support/ and told them about the plugin conflict with https://wordpress.org/themes/gridd/

Or perhaps I should select another Media Library ordering plugin....

**Comment by aristath** [comment]
Hmmm I just installed the plugin and checked, I couldn't replicate the issue on my localhost 🤔 
I can see however that they load all their assets in the customizer screen...
I assume it's because the media-library loads and they need to make categories etc available there.

**Comment by paaljoachim** [comment]
1. Made a local site with Desktop Server.
2. Add new theme and located Gridd and installed it. Then previewed it. Looked fine.
3. Exited without switching from Twenty Nineteen default theme.
4. Installed and activated Filebird plugin.
5. Went back to preview Gridd.
6. Error was seen. As can be seen in the issue.
7. Deactivated Filebird and then went to preview Grid. It showed up as it should.

**Comment by paaljoachim** [comment]
@aristath 
A followup. The customizer seems to suddenly be working again now.
I did a clone of the original dev site located here: 1dugnad.no.
Then installed the clone locally.

Updated the clone from gridd theme 1.0.7 to 2.0.1 and that worked great! Nice and smooth transition. As I am working on the local dev site the customizer began acting up again.
As I enter the customizer I am seeing just the widgets section but this time I am not able to scroll the customizer. It has frozen. I right clicked to see if there were any console errors and there was one:

![Screen Shot 2019-11-06 at 23 39 04](https://user-images.githubusercontent.com/5323259/68360597-a80f1a80-00ee-11ea-89c0-033d7fe114c7.png)

`script.js?ver=1.1.1:421 Uncaught TypeError: Cannot read property 'indexOf' of undefined
    at f.getColor (script.js?ver=1.1.1:421)
    at f.setBackgroundColorDetails (script.js?ver=1.1.1:410)
    at f.ready (script.js?ver=1.1.1:73)
    at Object.<anonymous> (customize-controls.min.js?ver=5.2.4:2)
    at i (load-scripts.php?c=1&load[]=jquery-core,jquery-migrate&ver=5.2.4:2)
    at Object.add [as done] (load-scripts.php?c=1&load[]=jquery-core,jquery-migrate&ver=5.2.4:2)
    at f.initialize (customize-controls.min.js?ver=5.2.4:2)
    at f.e.Class (customize-base.min.js?ver=5.2.4:1)
    at f [as constructor] (customize-base.min.js?ver=5.2.4:1)
    at new f (customize-base.min.js?ver=5.2.4:1)
getColor @ script.js?ver=1.1.1:421
setBackgroundColorDetails @ script.js?ver=1.1.1:410
ready @ script.js?ver=1.1.1:73
(anonymous) @ customize-controls.min.js?ver=5.2.4:2
i @ load-scripts.php?c=1&load[]=jquery-core,jquery-migrate&ver=5.2.4:2
add @ load-scripts.php?c=1&load[]=jquery-core,jquery-migrate&ver=5.2.4:2
initialize @ customize-controls.min.js?ver=5.2.4:2
e.Class @ customize-base.min.js?ver=5.2.4:1
f @ customize-base.min.js?ver=5.2.4:1
f @ customize-base.min.js?ver=5.2.4:1
(anonymous) @ customize-controls.min.js?ver=5.2.4:3
each @ load-scripts.php?c=1&load[]=jquery-core,jquery-migrate&ver=5.2.4:2
(anonymous) @ customize-controls.min.js?ver=5.2.4:3
i @ load-scripts.php?c=1&load[]=jquery-core,jquery-migrate&ver=5.2.4:2
fireWith @ load-scripts.php?c=1&load[]=jquery-core,jquery-migrate&ver=5.2.4:2
ready @ load-scripts.php?c=1&load[]=jquery-core,jquery-migrate&ver=5.2.4:2
J @ load-scripts.php?c=1&load[]=jquery-core,jquery-migrate&ver=5.2.4:2`


I turned on 
define('WP_DEBUG', true);
define( 'WP_DEBUG_LOG', true );

Then played around in the non-functioning customizer. Refreshed a few other pages but nothing showed up in the error log. I will keep it active for a while so see if anything shows up there. But atleast I got the above error message. I hope that helps.

**Comment by paaljoachim** [comment]
I deactivated Filebird but the customizer looked the same.
Then deactivated Gridd Plus 1.0.7 and suddenly the customizer looked normal.

**Comment by paaljoachim** [comment]
I am closing this for now as things just seems to be fixed.
