### ISSUE TITLE
Docs: How do I add a custom color to all links?

### ISSUE THREAD

**Issue by paaljoachim** [wplemon/gridd#149]
I am not sure how this is done so I thought I might as well ask here.

The client site I am working on is using this site today: https://celias.no/
There is a greenish color #76a8b0 that is used in the header, for various titles and for all links.
I am creating a new site for her in addition to the existing site she has today.

How do I setup the #76a8b0 color for all links and all titles etc?

Btw
This is one for the docs.

In the below screenshot we see the blue/green header color but a light blue links and underline color, and a black underline drop down arrow icon color. I need to change all of these to the same color as the header background color.

![Screen Shot 2019-11-07 at 12 24 02](https://user-images.githubusercontent.com/5323259/68412153-be05f500-0159-11ea-99c2-de5724abce2b.png)

**Comment by aristath** [comment]
You can't.
The whole point of this theme is to enforce good practices and accessible choices.
If you want to bypass the automatic colors selection for links, you can just add some custom css:
```
a {color: #76a8b0;}`
```

**Comment by paaljoachim** [comment]
I am looking at using a custom color for hovering over links. Text, underline and the drop down arrow. It was possible to pre 2.0 set a custom link color, but it seems like that is not possible any longer. Accessibility should not remove options a user chooses to use. One can do informed decisions. Meaning selecting a custom color a message could show up saying that it would be better to leave it on automatic for accessible reasons to create a better contrast of text color and link color.

**Comment by paaljoachim** [comment]
The client as the menu to be as close to possible as she has on her original site: https://celias.no/ So I am trying to use the available customizer options (if those exist) to copy what is on that site.
