### ISSUE TITLE
Docs: How to add space above Header and below footer.

### ISSUE THREAD

**Issue by paaljoachim** [wplemon/gridd#150]
Hey

For instance this web site I made a bunch of years ago using Genesis:
https://kanyini.org/ 

Has a margin header top and a footer bottom. Giving space in both the top and bottom for the background image to show through. (I notice I also have the header background set to transparent.)

![Screen Shot 2019-11-07 at 11 56 15](https://user-images.githubusercontent.com/5323259/68409749-a4fb4500-0155-11ea-960e-5f50460a4083.png)

An example with the Gridd theme.
In changing Content Maximum Width to 45em.
Added some Header padding.
In the Main Grid Layout added 10px to the Grid Container Gap.

My question is then should there be a margin option in the header and footer?

![Screen Shot 2019-11-07 at 12 00 54](https://user-images.githubusercontent.com/5323259/68410171-4bdfe100-0156-11ea-810f-69164a294d7b.png)

So that one can add a top margin to the header pushing it down and a bottom margin pushing the footer up. Having the background shine through similar to the screenshot I took of the kanyini.org web site seen above here.

**Comment by aristath** [comment]
Margins are not really necessary here... You could just add a new row in your grid and set its height to 50px or whatever you want. You don't have to put anything in that row, it can just be empty.
So you could have something like this:

![Screenshot_2019-11-09 Customize localhost – Just another WordPress site(1)](https://user-images.githubusercontent.com/588688/68529016-9f8f2d80-0302-11ea-9781-73f321846e77.png)

The only thing missing here to be able to achieve the layout you want is transparent header background. But that is already achievable in Gridd-Plus, so I'm not sure we need to do anything here

**Comment by paaljoachim** [comment]
Ahhh that is really cleaver! I did not think of adding a row above the header and below the footer!
We got to add this to the docs. I changed the title of the issue and will update this issue to show with screenshots how to add space above the header and below the footer to create the effect that I have at kanyini.org.

**Comment by paaljoachim** [comment]
I made a Wiki for this here: https://github.com/wplemon/gridd/wiki/Exploring-the-Grid
