### ISSUE TITLE
Docs: Code examples for the child theme functions file.

### ISSUE THREAD

**Issue by paaljoachim** [wplemon/gridd#152]
Hey Ari

I am adding this issue as it would be very interesting having various code examples we can add to the child theme functions file in the wiki.

Most child themes have a style.css file. To call this in to the child theme functions.php file add this code:

```
add_action( 'wp_enqueue_scripts', function() {
	wp_enqueue_style( 'child-style', get_stylesheet_uri() );
});
```

One can also add additional code to the functions file to begin with specific customizer setups.......

**Comment by aristath** [comment]
This is not specific to this theme. Creating a child theme is the same for all themes and there are hundreds of articles out there for these things.
I'd rather focus on documenting the theme-options, what they do and how to use them 😆 

I agree that adding docs for these things would be useful, but it shouldn't be the primary focus

**Comment by paaljoachim** [comment]
Well as the focus is on a child theme for Gridd. There will be just a little general child theme code and then theme specific examples that would be good to include.

**Comment by paaljoachim** [comment]
I added this wiki.
https://github.com/wplemon/gridd/wiki/Creating-a-child-theme

**Comment by paaljoachim** [comment]
I will just close this issue as I have added the above wiki where we can add additional information if/when needed.
