### ISSUE TITLE
Create a filter to easily change the drop down arrow.

### ISSUE THREAD

**Issue by paaljoachim** [wplemon/gridd#154]
As you just mentioned this in slack I thought I might as well create an issue for it.
It would be great with an easy way to change the drop down arrow unicode so one can choose from a broad variety of arrow types.

**Comment by aristath** [comment]
Actually we don't need to add a filter, we could just use the native WP filters:

```php
add_filter( 'walker_nav_menu_start_el', function( $item_output, $item ) {
    return str_replace( '⌵', '⇣', $item_output );
}, 20, 2 );
```

**Comment by paaljoachim** [comment]
Ahhh that is interesting! Thank you Ari!
