### ISSUE TITLE
Social media block - adding a frontend CSS

### ISSUE THREAD

**Issue by paaljoachim** [wplemon/gridd#161]
Hey Ari

As I used the Social Media Block.
The frontend looked like this: 
<img width="388" alt="Screen Shot 2020-01-16 at 12 53 18" src="https://user-images.githubusercontent.com/5323259/72523008-2e6a7a00-385f-11ea-8bac-5f63f4623a5b.png">

The backend one could choose from multiple styles. I selected this:
![Screen Shot 2020-01-16 at 12 53 31](https://user-images.githubusercontent.com/5323259/72523056-480bc180-385f-11ea-9766-a34bc7f0c291.png)

It would be great to have the frontend reflect the backend.
https://github.com/WordPress/gutenberg/issues/19020

--------

I added the following CSS into the style.css.

```
.wp-social-link svg {  
	width: 50px;
    height: 50px;
    border-radius: 25px;
    padding: 8px;
	margin-right: 10px;
	background: #167ac6;
	float: left;
}

.wp-social-link a {
	fill: #fff;
}

.wp-social-link a:active, 
.wp-social-link a:hover {
	fill: #c65c00;
}
```

It now looks like this on the frontend:
<img width="480" alt="Screen Shot 2020-01-17 at 01 26 59" src="https://user-images.githubusercontent.com/5323259/72574192-7d002e80-38c8-11ea-9bf7-5b132f740d5a.png">

**Comment by aristath** [comment]
Styles for that will be added once the block lands in wp-core ;)

**Comment by paaljoachim** [comment]
This has been fixed.
