### ISSUE TITLE
Backend Gutenberg layout area

### ISSUE THREAD

**Issue by paaljoachim** [wplemon/gridd#165]
I am on a Macbook Pro running a default resolution of 15,4-inch (2880 x 1800).

Gridd 3

<img width="1106" alt="Screen Shot 2020-03-07 at 14 13 48" src="https://user-images.githubusercontent.com/5323259/76144156-ebb66880-607d-11ea-9d8a-fea106b2286a.png">

Twenty Twenty theme

<img width="1106" alt="Screen Shot 2020-03-07 at 14 15 52" src="https://user-images.githubusercontent.com/5323259/76144231-713a1880-607e-11ea-9da7-c9a5c6060eae.png">

The main thing I notice is the small font used for "Add title" in Gridd and the "Start writing or type / to choose a block". "Start writing..." is actually smaller then the sidebar settings font.
I am also not seeing the author below Pending Review.

The contrast is huge when looking at the backend vs the frontend. It would be better to adjust the backend of Gridd in regards to font size so it looks more similar to the frontend.

**Comment by paaljoachim** [comment]
Ahhh interesting. 
I could not save, and decided to go to permalinks and resave them. Then back again to create a new page. This time the Author name showed up and I was able to save.

**Comment by paaljoachim** [comment]
One more thing...

Bottom breadcrumbs:
<img width="1143" alt="Screen Shot 2020-03-07 at 14 48 01" src="https://user-images.githubusercontent.com/5323259/76144628-b6f8e000-6082-11ea-8461-50ba108df7e1.png">


<img width="1151" alt="Screen Shot 2020-03-07 at 14 47 50" src="https://user-images.githubusercontent.com/5323259/76144632-bc562a80-6082-11ea-9038-6f2b81eb81dc.png">

**Comment by aristath** [comment]
> The main thing I notice is the small font used for "Add title" in Gridd and the "Start writing or type / to choose a block". "Start writing..." is actually smaller then the sidebar settings font.

That would actually depend on the typography settings in the customizer... The thing is that typography-size would depend on the responsive-typography settings combined with the screen-size.
twentytwenty uses a constant font-size for all screen-sizes. However in Gridd, if you set the "Fluid Typography Ratio" high, then the smaller the screen-size gets, the smaller the letters will get until they reach the body font-size defined in your settings.

With the default Gridd settings btw this is what I see:

![Screenshot_2020-03-07 Edit Post ‹ lemon — WordPress](https://user-images.githubusercontent.com/588688/76145387-b582e400-6091-11ea-8e32-3a57d933ca8c.png)

> Bottom breadcrumbs

As seen in the screenshot above, they seem to be there.

BTW I'm running WP 5.4-RC, without the Gutenberg plugin installed. Perhaps that's where our installations differ?

**Comment by paaljoachim** [comment]
I am using WP 5.3. So yeah that might create a difference. I will download the beta plugin and install 5.4 and see how it looks.

**Comment by paaljoachim** [comment]
I am just closing this for now.... if needed I will reopen.
