### ISSUE TITLE
Button block starts out with no background and no font color

### ISSUE THREAD

**Issue by paaljoachim** [wplemon/gridd#166]
The buttons block default look:
<img width="928" alt="Screen Shot 2020-03-07 at 14 40 34" src="https://user-images.githubusercontent.com/5323259/76144516-a3994500-6081-11ea-8564-af481692b722.png">

**Comment by aristath** [comment]
When you're focused on a button, the focus/hover styles are used. If you click anywhere outside the button, the browser loses focus and the normal styles are used. If you then hover the button you'll see what I mean... Clicking on the button to edit it again brings the browser focus to the button again, so the focus styles are used.

**Comment by paaljoachim** [comment]
Btw I am testing without using the Gutenberg plugin.
This is what I am seeing:

![Gridd-Buttons-Block](https://user-images.githubusercontent.com/5323259/76145343-f75b5c80-6088-11ea-905b-7b651a076aec.gif)

**Comment by aristath** [comment]
fixed
