### ISSUE TITLE
Body background color not seen in backend Gutenberg layout

### ISSUE THREAD

**Issue by paaljoachim** [wplemon/gridd#168]
NB! EDIT - I did this after filling in the below isse.
I took a backup of the maguti live site and downloaded it and made a local version.
Going from Gutenberg 7.6 to 7.7 removes the body background color in backend Gutenberg with Gridd dev.

-----------------

On to the issue.

I am recreating the maguti site using a beta of 5.4 and the dev version Gridd.

I added a background
![Screen Shot 2020-03-15 at 10 14 00](https://user-images.githubusercontent.com/5323259/76699467-086e2400-66ae-11ea-978e-30f0dba93621.png)

The frontend
![Screen Shot 2020-03-15 at 10 14 45](https://user-images.githubusercontent.com/5323259/76699472-115ef580-66ae-11ea-9ac3-daed6c8a4814.png)

(O btw the cover full width is not showing up full width. See the above cover image used. Image is fixed. I can add another issue for that.)

The backend
![Screen Shot 2020-03-15 at 10 15 01](https://user-images.githubusercontent.com/5323259/76699502-4408ee00-66ae-11ea-839d-e69497a597be.png)

**Comment by aristath** [comment]
Good catch!
The problem here was inheritance.
The editor was trying to get the color of the content-background, however in this case there was no override color for the content, so it should inherit the global background setting.

Fixed.
