### ISSUE TITLE
Cover Block full width not showing up as full width

### ISSUE THREAD

**Issue by paaljoachim** [wplemon/gridd#169]
I am using a child theme and Gridd. WP beta 5.4. Gutenberg plugin 7.7

![Screen Shot 2020-03-15 at 11 17 22](https://user-images.githubusercontent.com/5323259/76699533-9f3ae080-66ae-11ea-8a66-70e01648d3ea.png)

Frontend result.
![Screen Shot 2020-03-15 at 11 17 33](https://user-images.githubusercontent.com/5323259/76699536-a3ff9480-66ae-11ea-8223-d7e2f15066fd.png)

Notice that even though I selected Full Width. The Cover image is not showing up as full width on the frontend.

**Comment by aristath** [comment]
This one is weird, I can't replicate on localhost after updating everything :thinking:

**Comment by paaljoachim** [comment]
Aha!

Click the Fixed background and then check the frontend.

![Screen Shot 2020-04-05 at 22 12 07](https://user-images.githubusercontent.com/5323259/78508895-893eae00-778a-11ea-82b7-1774253676b9.png)

![Screen Shot 2020-04-05 at 22 12 43](https://user-images.githubusercontent.com/5323259/78508907-98bdf700-778a-11ea-9de7-b42e7932c81c.png)

**Comment by aristath** [comment]
I believe this one is OK now that all styles were updated

**Comment by paaljoachim** [comment]
I will download the newest dev version and test out...

**Comment by paaljoachim** [comment]
It looks like it is working nicely now..:)
