### ISSUE TITLE
Navigation Block missing CSS on frontend

### ISSUE THREAD

**Issue by paaljoachim** [wplemon/gridd#170]
Hey Ari

I am working on an experimental site.
I added a nav block.

Here is the Gutenberg backend.
![Screen Shot 2020-04-05 at 22 14 27](https://user-images.githubusercontent.com/5323259/78509021-51843600-778b-11ea-99c0-f02665bebb6c.png)

Frontend:
![Screen Shot 2020-04-05 at 22 14 35](https://user-images.githubusercontent.com/5323259/78509024-5b0d9e00-778b-11ea-99f4-c80ee1520037.png)

**Comment by paaljoachim** [comment]
Using https://webkonsulenten.com/

Chrome
WordPress 5.4
Gutenberg 7.9.1

I added a submenu. (how this looks is a Gutenberg issue.) The point is the submenu.
![Screen Shot 2020-04-23 at 09 44 50](https://user-images.githubusercontent.com/5323259/80073557-3b76c380-8548-11ea-8d79-c3da95119057.png)

Frontend:
![Screen Shot 2020-04-23 at 09 45 05](https://user-images.githubusercontent.com/5323259/80073629-55b0a180-8548-11ea-94ec-5fe7974b2c55.png)

Clicking the arrow nothing happens.

**Comment by aristath** [comment]
Once the nav block is merged in wp-core I will be migrating the normal navigation to use that block, so at that point the css etc for menus will be refactored.
Right now the nav block is still somewhat experimental and under heavy construction in the Gutenberg repo so all I'm doing for it is include the core Gutenberg styles.
The arrow _may_ be coming from the normal navigation of Gridd, I haven't checked.

Can you think of a reason why we'd need the nav block right now? (besides testing/experimenting)
