### ISSUE TITLE
New feature: Breadcrumbs

### ISSUE THREAD

**Issue by paaljoachim** [wplemon/gridd#173]
I am thinking a breadcrumbs feature which one can turn on in the customizer or using code snippets. 

If code snippets then it would be good to add a Wiki doc for various customization that can be done.

Here is an example from a Norwegian religious organization web site I made.
<img width="1329" alt="Screen Shot 2020-04-23 at 23 28 48" src="https://user-images.githubusercontent.com/5323259/80151403-4833ff80-85ba-11ea-954e-294a177447af.png">

<img width="1327" alt="Screen Shot 2020-04-23 at 23 30 22" src="https://user-images.githubusercontent.com/5323259/80151473-6b5eaf00-85ba-11ea-853c-44b919fca7d2.png">

**Comment by aristath** [comment]
There is already a breadcrumbs grid-part in the theme!

**Comment by paaljoachim** [comment]
Hmm I am looking but have not found it yet..... it is likely somewhere in the customizer....

**Comment by paaljoachim** [comment]
Notes to myself...
Add a new row in the Grid Layout. 
Then select the Breadcrumbs Grid part. 
Gradually move the Breadcrumbs row from the bottom and up to just above the content.
