### ISSUE TITLE
Checking image alignments

### ISSUE THREAD

**Issue by paaljoachim** [wplemon/gridd#176]
Hey Ari

Testing newest dev.

Here is an example of aligning an image Full Width.

![Screen Shot 2020-04-25 at 19 33 25](https://user-images.githubusercontent.com/5323259/80286450-cc59c480-872b-11ea-90ca-260b6247d5d1.png)

![Screen Shot 2020-04-25 at 19 32 59](https://user-images.githubusercontent.com/5323259/80286458-d8de1d00-872b-11ea-95e3-45937aa0800c.png)

![Screen Shot 2020-04-25 at 19 35 12](https://user-images.githubusercontent.com/5323259/80286481-e85d6600-872b-11ea-8986-9e6c864ffebf.png)

**Comment by aristath** [comment]
I don't see any issues here on my localhost... The theme now uses the core styles from Gutenberg so there shouldn't be any issues like this :thinking:

**Comment by paaljoachim** [comment]
I will need to look into it later tonight....
It is now time for a dinner and a movie....:)

**Comment by paaljoachim** [comment]
It looks like it is working pretty good on the frontend.
![Screen Shot 2020-04-26 at 11 51 20](https://user-images.githubusercontent.com/5323259/80304104-61080500-87b4-11ea-979c-011e2d498b18.png)

There are some small white gaps on the left and right side.

Going to the backend. Making the window bigger then I see the end of the image on the right side. I guess that does not matter. But I was expecting the image to stretch across also on the backend.
![Screen Shot 2020-04-26 at 11 51 43](https://user-images.githubusercontent.com/5323259/80304139-8563e180-87b4-11ea-93e0-db86d26215d5.png)

**Comment by aristath** [comment]
I was able to replicate today, turns out this was caused by some recent changes in Gutenberg.
Fixed.
