### ISSUE TITLE
Deprecated footer even on new site

### ISSUE THREAD

**Issue by paaljoachim** [wplemon/gridd#177]
Hey Ari

I made a new local site and uploaded the newest version of Grid to it.
Even with a new site I am seeing this:

![Screen Shot 2020-04-26 at 11 33 01](https://user-images.githubusercontent.com/5323259/80303641-be4e8700-87b1-11ea-910c-a1ffe6ee972f.png)

Desktop Server local site.
WordPress 5.4
Default plugins Akismet and Hello Dolly
Chrome

**Comment by aristath** [comment]
good catch, fixed
