### ISSUE TITLE
Extra wide underline in menu

### ISSUE THREAD

**Issue by paaljoachim** [wplemon/gridd#179]
Hey Ari

I happen to notice this:
![Screen Shot 2020-04-26 at 13 18 18](https://user-images.githubusercontent.com/5323259/80305956-84d14800-87c0-11ea-90a1-f05efb867f03.png)

https://mytestingbox.com/a-title/
WordPress 5.4
Chrome
Multisite main site.
Gutenberg plugin 7.9.1

**Comment by aristath** [comment]
Looks OK now on your test site, I assume this has been resolved?

**Comment by paaljoachim** [comment]
I just uploaded todays newest dev version to designkurs.com. Then checked the customizer. It is a lot better so I will close this issue.
