### ISSUE TITLE
Customizing breadcrumbs

### ISSUE THREAD

**Issue by paaljoachim** [wplemon/gridd#180]
I cloned https://religionskritikk.no/
and made a local site and activated the newest Gridd development version.

Added an area for Breadcrumbs.

![Screen Shot 2020-04-28 at 13 17 28](https://user-images.githubusercontent.com/5323259/80481400-a104ee80-8952-11ea-82a0-856709dd8f66.png)

A few things I notice right away. That the Breadcrumbs does not left align with the content below. The font size is the same as the nav. I see a white background color (which I can probably remove in the customizer.)

I went and added a Gutenberg Breadcrumbs issue: https://github.com/WordPress/gutenberg/issues/21943

**Comment by paaljoachim** [comment]
Btw I noticed this:
```
.gridd-tp-breadcrumbs.custom-options {
    --bg: #ffffff;
    --mw: 85%;
    --cl: #000000;
}
```
Through the Additional CSS section I adjusted the above to become:
```
.gridd-tp-breadcrumbs.custom-options {
    --bg: #f5f7f9;
    --mw: 85%;
    --cl: #000000;
}
```
So that I would have the same greyish background color as the content area.

**Comment by aristath** [comment]
> the Breadcrumbs does not left align with the content below. The font size is the same as the nav. I see a white background color (which I can probably remove in the customizer.)

Customizer > Theme Options > Breadcrumbs.
Turn the inherit/override option to override. You can adjust the breadcrumbs width there, and make it the same as your content. You can also tweak the background-color there...

Regarding the CSS you added, you don't need to if you customize the options in the Breadcrumbs section :)
