### ISSUE TITLE
Category pages post grid

### ISSUE THREAD

**Issue by paaljoachim** [wplemon/gridd#184]
Customizer -> Post Archives Options.
Posts Mode

Selecting the first option.
Then Wide
Then Display "Posts" archives as a grid.
I see this:

![Screen Shot 2020-04-28 at 14 58 12](https://user-images.githubusercontent.com/5323259/80489834-baad3280-8960-11ea-9b47-a9e92fbde1c3.png)

A very tall and wide featured image, and posts below each other with very tall and wide images.

---

In clicking **Display "Posts" archives as a grid** I see no difference in the customizer.
As I expected to see a grid kind of layout, but I just see the posts below each other in a standard way. Clicking the Normal option shows posts below each other with regular sized featured images.

**Comment by aristath** [comment]
I can't replicate this one :thinking:

**Comment by paaljoachim** [comment]
We will just skip this issue as well.
