### ISSUE TITLE
Adjusting Posted on meta data to Date

### ISSUE THREAD

**Issue by paaljoachim** [wplemon/gridd#187]
I am once again comparing:
https://religionskritikk.no/nettmagasin/de-usynlige-krista-gudefodersken-kirkemodrene-og-gud-moder/

Just below the title this is seen.
**Dato 29. april 2020** 
Dato = Date

![Screen Shot 2020-04-29 at 18 06 47](https://user-images.githubusercontent.com/5323259/80618853-37fda380-8a44-11ea-89ed-4e0a2c14f919.png)

To the dev site using dev version of Gridd:
**Posted on 29.april 2020 by redaktor**

![Screen Shot 2020-04-29 at 18 07 22](https://user-images.githubusercontent.com/5323259/80618904-4a77dd00-8a44-11ea-8df3-3a745f153da2.png)

How would I change the **Posted on 29.april 2020 by redaktor** used in the Gridd theme to **Dato 29. april 2020** ?

**Comment by aristath** [comment]
Hmmm right now I suppose the easiest method would be in a child theme, overriding the `template-parts/part-post-date-author.php` file

**Comment by paaljoachim** [comment]
Ahh tweaking the translation is a good idea.
I am wondering if I should just close this issue. 
Then just leave it up to Full Site Editing later on.
