### ISSUE TITLE
New single post options

### ISSUE THREAD

**Issue by paaljoachim** [wplemon/gridd#188]
Associated issues:
**How to show post categories and tags in a post blog?**
https://github.com/wplemon/gridd/issues/186
and
**Adjusting Posted on meta data to Date**
https://github.com/wplemon/gridd/issues/187

I have been using the Beans framework for a few years. 
I am looking into transferring a few client sites over til Gridd.

Regarding the two issues above. 
One is about showing post categories and tags at the bottom of a post.
The second is about adjusting the Posted on -date- by -author- to Posted Date.

My suggestion would be to add options into the customizer here:
![Screen Shot 2020-05-01 at 14 26 21](https://user-images.githubusercontent.com/5323259/80805223-c0508580-8bb7-11ea-9cf3-279b22696090.png)

1st option. 
Checkbox - show categories and tags.
Bottom or top.

2nd option
A field box with this text: "Posted on -date- by -author-"
(Another field box below.) Change to: -fill in anything you want- here are some commands to use -date-, -author-, -comments-, -categories-, -tags- etc

Or a kind of mix of option 1 and 2.

**Comment by aristath** [comment]
I agree there should be options for these, but before I go ahead and add new options that we'll then have to deprecate as we move things to Gutenberg, can you think of a better way to do it perhaps in the editor somehow? :thinking:

**Comment by paaljoachim** [comment]
Hey Ari. Good question in regards to a possible way to add this in Gutenberg.
I will just close this issue, as this will one of the many things that will likely be solved in Full Site Editing.
