### ISSUE TITLE
customizer: Header color not seen

### ISSUE THREAD

**Issue by paaljoachim** [wplemon/gridd#189]
I am experimenting with adding the newest Gridd development theme to a new local site for easywebdesigntutorials.com.

In the customizer I turned on Override Options then set the header background color. The header color is not seen, so it seems there is something I am missing...
![Screen Shot 2020-05-22 at 00 54 53](https://user-images.githubusercontent.com/5323259/82614125-5a0fbf00-9bc7-11ea-9f0a-ee974b443ae2.png)

I then set the footer background color. That showed up.
![Screen Shot 2020-05-22 at 00 55 28](https://user-images.githubusercontent.com/5323259/82614138-6136cd00-9bc7-11ea-8856-45562b32bf26.png)

**Comment by aristath** [comment]
The Inheritace goes like this: `Global -> Header -> Branding`
If the branding and navigation parts don't override, then the header-background will be shown.
My guess is simply that they get overriden in the parts (branding & navigation) themselves

**Comment by paaljoachim** [comment]
Should inheritance by default be turned on?
As it would right away leave the door open for Global options. 

Going to Theme Options -> going through the main options in this list.
Main Grid Layout
Header Grid
Footer Grid
Typography

Content - Override Options
Header - Override Options  
Footer - Override Options
Breadcrumbs - Override Options
Navigation1 - Override Options

What is missing from the above is the Branding area.

One more thing.
I added Navigation 2 and Navigation 3 to use the same menu as in Navigation 1 just to see where they showed up in the customizer.  As I did kinda expect Nav 2 to show up directly below Nav 1. I also expected Nav 3 to show up in the footer.

**Comment by aristath** [comment]
On a new installation they do inherit, the default value for all the inherit/override switches in to inherit. I just tested it on a new installation and can confirm it is the case.
However, if there was installed a previous version of the theme on that site, then on update the settings are set to override when the migration script runs, so that any custom color options can be applied.

**Comment by paaljoachim** [comment]
Hmm strange. I just built a new local dev site yesterday using the latest development version of Gridd and even though I override the Header I am not seeing the orange color I added.
Hmm I might just need to build another local site testing it again.

**Comment by paaljoachim** [comment]
Aha! I activated the parent Gridd dev theme and Header Override works there, but using a child theme with just some very few modifications the Header Override is not working. Here is the child theme I am using: https://www.dropbox.com/s/rsc5q07rjxbht4u/gridd-child.zip?dl=0

**Comment by paaljoachim** [comment]
I updated to version 3.0. Checked to see the header override color in place. Then switched to the child theme. I did not notice the orange color. Here is an inspect on the fronend.

![Screen Shot 2020-05-24 at 13 51 58](https://user-images.githubusercontent.com/5323259/82753439-ee477500-9dc5-11ea-93e2-c1eb539b70af.png)

**Comment by paaljoachim** [comment]
Alrighty. As I could affect all the various areas in the same section I wondered where Branding was located. It was then moved to Site Identity section.
