### ISSUE TITLE
Meta boxes / Custom fields are fixed should be at bottom of screen

### ISSUE THREAD

**Issue by paaljoachim** [wplemon/gridd#192]
Hey Ari

Meta boxes / Custom fields such as this Excerpt is fixed/sticked to the bottom of the viewport. It should instead be at the bottom of the document layout.

![Screen Shot 2020-06-03 at 15 49 08](https://user-images.githubusercontent.com/5323259/83644629-c7512600-a5b1-11ea-8da7-103acd31e262.png)

It becomes visually distractive having it fixed to the bottom of the viewport.

---

Example Twenty Twenty theme.
Excerpt meta box will not show up before I have scrolled to the bottom of the screen.
![Screen Shot 2020-06-03 at 15 50 24](https://user-images.githubusercontent.com/5323259/83644834-02535980-a5b2-11ea-98cd-a94957dc65e0.png)

It is a lot better to have it at the bottom of the document layout screen similar to Twenty Twenty.
Btw I also tried removing the grey color around the meta boxes, but I was not able to do so.

**Comment by aristath** [comment]
Caused by a recent change in Gutenberg. Fixed, included in v3.0.7
