### ISSUE TITLE
Block_Styles esc_html breaks some css rules

### ISSUE THREAD

**Issue by markisatacomputer** [wplemon/gridd#201]
Hello.  I''ve created a child theme from Gridd and I'm using the block css override folder.  I've added a few rules that use the child combinator and they are broken when included inline and escaped for html.  Here's my rule:
```
.gridd-site-wrapper .contodo.two-up .content > * {
	padding-left: 0;
	padding-right: 0;
}
```
which is transformed to
```
.gridd-site-wrapper .contodo.two-up .content &gt; * {
	padding-left: 0;
	padding-right: 0;
}
```

I really like the minimal imprint of including css this way so I'd love to keep using this feature.  Any advice for me here?

**Comment by aristath** [comment]
Good catch!
Fixed and released an update :+1:

**Comment by markisatacomputer** [comment]
Thanks @aristath!
