### ISSUE TITLE
FYI: Jetpack will be deprecating and removing the `jetpack_require_lib` function

### ISSUE THREAD

**Issue by anomiex** [wplemon/gridd#205]
We're planning on deprecating and removing the `jetpack_require_lib` function from Jetpack, and a search of the WordPress Theme directory turned up your theme as the only one using it.

It looks like you're using existence of the function to determine if Jetpack is active. You might change your check to look for whether one of Jetpack's constants (such as `JETPACK__VERSION` or `JETPACK__PLUGIN_DIR`) is defined instead, or if the check is needed late enough you could check for `class_exists( \Tonesque::class )` directly instead of trying to detect the specific plugin at all.

**Comment by aristath** [comment]
Thank you! I converted the checks to use the constant 👍
