### ISSUE TITLE
Add a light-box option for single image and gallery

### ISSUE THREAD

**Issue by vbaimas** [wplemon/gridd#52]
**Description**
So gar,  the light-box option for single image and gallery is not applied.

**Screenshots**
![default option](https://cl.ly/9cf2122fdf06/Screen%20Recording%202019-07-12%20at%2002.32%20PM.gif)

**Thoughts**
Maybe this option give us some extra kb, but I think that it is an important feature for the user.

**Example** 

![example](https://cl.ly/09c2d96343e7/Screen%20Recording%202019-07-12%20at%2002.40%20PM.gif)

**Suggestion**
We can use a pop up plugin like this. https://github.com/dimsemenov/Magnific-Popup or something that does the job that we need without being very large.

**Comment by aristath** [comment]
Discussed on slack, closing this one as `wontfix`.
Users can install any plugin they want for lightboxes.
