### ISSUE TITLE
Change typography on site title and tagline section

### ISSUE THREAD

**Issue by vbaimas** [wplemon/gridd#53]
The typography settings of customizer do not allow the user to change typography on site title and tagline. Of course I do not know if this is given as an extra feature in gridd plus.

**Fact**
We give the user the option to display this section or not. From the other hand this is text and I think that we should give the possibility to be parameterized, once we do it for the body and the header of theme.

**Comment by aristath** [comment]
There already was a control to change the typography for these, but was hidden due to a bug.
Fixed in the `develop` branch.
