### ISSUE TITLE
The mobile menu is not working (version: 1.1.8)

### ISSUE THREAD

**Issue by vbaimas** [wplemon/gridd#54]
I just realized that the mobile menu is not working in version: 1.1.8.

PS :  _The mobile navigation is enabled from the `Mobile Navigation > Enable Mobile Navigation`_

![mobile navigation](https://cl.ly/dbf19a72c35d/Screen%20Recording%202019-07-12%20at%2005.31%20PM.gif)

**Comment by aristath** [comment]
Looks like there is no menu assigned for mobile-navigation.
You can assign one from Customizer > Menus > View All Locations > Mobile Navigation

**Comment by vbaimas** [comment]
Xm.. Thanks @aristath. I'm sorry for this but I was confused.
