### ISSUE TITLE
Impove the accessibillity of search form

### ISSUE THREAD

**Issue by vbaimas** [wplemon/gridd#55]
- Include a meaningful description in the label. We can do that by giving the option from customizer.

So, instead of a simple one "search", the user will be able to change this label from the customizer.

Some examples in action : 

`search`   > `search for recipe`
`search`   > `search for news`

- Also we can use the powerfull option of `Color Vision Deficiencies Simulator` to improve the default style of border color and the style of border color in focus. [[screenshot](https://user-images.githubusercontent.com/5068068/61276532-e6d43a00-a7b8-11e9-8db6-6a9160523a5f.png)]

- Change the background color of button on hover mode.

**Comment by aristath** [comment]
Search is global, it doesn't refer to a specific post-type therefore it can't be "search recipes" etc.
If the user installs a plugin to limit or alter the search query, then these plugins usually provide their own searchform so they can simply use that instead.

The search styles follow the global button styles and I agree these can be improved, but I don't understand what this has to do with the color-blindness simulator :thinking:

**Comment by aristath** [comment]
Searchform changed in the develop branch, closing this one
