### ISSUE TITLE
Add search icon

### ISSUE THREAD

**Issue by paaljoachim** [wplemon/gridd#61]
It would be great to have a search icon to add to the header area. As an option to the search field that exists today.

**Comment by aristath** [comment]
The searchform was improved in https://github.com/wplemon/gridd/commit/30ed7bce1896ca549894725ee8478e9fb3990711
Currently in the `develop` branch, this will be included in v1.1.11 which will be released later today.
The new searchform looks like this: 
![Screenshot_2019-07-28 Gridd(1)](https://user-images.githubusercontent.com/588688/62005429-b935ac00-b13b-11e9-9bf9-06969761a526.png)
The actual width of the searchform in headers can be tweaked by editing the column's width inside the header-grid (see red circle in screenshot below)
![image8356](https://user-images.githubusercontent.com/588688/62005460-5264c280-b13c-11e9-8e45-a917897e164f.png)

**Comment by aristath** [comment]
Closing this one since v1.1.11 was just released.

**Comment by paaljoachim** [comment]
I am looking forward to a simple click a search icon and have a search area open. To have a much smaller footer print of the search area seen at all times.
