### ISSUE TITLE
Header image not visible

### ISSUE THREAD

**Issue by paaljoachim** [wplemon/gridd#69]
In the Theme Options -> Header

I added a new image and did not crop it. The image did not show up in the header.

I noticed this text:
Click “Add new image” to upload an image file from your computer. Your theme works best with an image with a header height of 0 pixels — you’ll be able to crop your image once you upload it for a perfect fit.

I do not know what is meant with "header height of 0 pixels"

**Comment by aristath** [comment]
Problem here is the fact the wp-core doesn't allow filtering or changing the description of the default background controls for headers.
Added a workaround and the fix will be included in v1.1.12.
The description was changed to this:
> Choose a background image for your header. Please note that the image will only be visible if the grid parts in your header use transparent colors, or if you are using a grid-gap for your header grid.
