### ISSUE TITLE
Auto updating the theme from Github?

### ISSUE THREAD

**Issue by paaljoachim** [wplemon/gridd#70]
I am wondering if we can auto update the theme directly from Github?

**Comment by aristath** [comment]
We could if the theme wasn't hosted on w.org... 
In fact I had a script that was serving updates from github while the theme was under review, I couldn't wait 3 months :laughing: 
However now that the theme is officially in the WordPress repository we can't include scripts like that.

**Comment by paaljoachim** [comment]
Gotcha!
