### ISSUE TITLE
Creating a child theme

### ISSUE THREAD

**Issue by paaljoachim** [wplemon/gridd#81]
It would be helpful to have a child theme available for download meant to be used with the Gridd theme.

**Comment by paaljoachim** [comment]
@aristath 

Here is the child theme functions file code that I am using.

`<?php

// Enqueue parent styles and load child styles.
// https://developer.wordpress.org/themes/advanced-topics/child-themes/
add_action( 'wp_enqueue_scripts', 'my_theme_enqueue_styles' );
function my_theme_enqueue_styles() {
 
    $parent_style = 'parent-style'; // This is style for the Gridd theme.
 
    wp_enqueue_style( $parent_style, get_template_directory_uri() . '/style.css' );
    wp_enqueue_style( 'child-style',
        get_stylesheet_directory_uri() . '/style.css',
        array( $parent_style ),
        wp_get_theme()->get('Version')
    );
}`

Let me know if I should adjust he code I am using.

**Comment by aristath** [comment]
Gridd doesn't enqueue a stylesheet since everything gets added inline when needed.

The above code should be simplified. This will achieve the same thing:

```php
add_action( 'wp_enqueue_scripts', function() {
	wp_enqueue_style( 'child-style', get_stylesheet_uri() );
});
```

The difference here is that we don't enqueue the parent theme's stylesheet (it's not needed), and we don't define an array of dependencies or a version. For the purposes of a child theme here these are not needed. I also replaced this line:
```php
get_stylesheet_directory_uri() . '/style.css',
```
with a simple call to `get_stylesheet_uri()`, they are exactly the same.

**Comment by paaljoachim** [comment]
Bottom line is this:
Child theme functions.php needs to contain this code.

add_action( 'wp_enqueue_scripts', function() {
	wp_enqueue_style( 'child-style', get_stylesheet_uri() );
});

I changed the title of the issue, as this is info for the docs about information that needs to be added to the child theme functions file.

**Comment by aristath** [comment]
>  Child theme functions.php needs to contain this code.

No, it doesn't.
That code enqueues the style theme's `styles.css` file.
Not all child themes however need that. If you add your styles in the customizer's Custom-CSS field then you can get rid of that code from your functions.php as well.

For the docs I was thinking of using the repository's wiki... It's a simple and effective method.
