### ISSUE TITLE
Overwriting color is only seen on the frontend.

### ISSUE THREAD

**Issue by paaljoachim** [wplemon/gridd#86]
I went to the Footer Grid. Added a Footer background color of green. Then clicked the Override Footer Parts Background setting. I expected to see the green color behind the full footer. What I saw was this:

![Screen Shot 2019-08-13 at 23 22 59](https://user-images.githubusercontent.com/5323259/62978482-a8ff1b80-be21-11e9-989f-81b88b584412.png)

Just a tiny area on the right bottom area became green.
I just checked the frontend and the full footer is now green.

<img width="1459" alt="Screen Shot 2019-08-13 at 23 27 10" src="https://user-images.githubusercontent.com/5323259/62978579-e663a900-be21-11e9-883c-d8d7e1e1c50c.png">

It seems the overwrite option just is seen on the frontend and not in the customizer.

-------

Going back again to the customizer the background footer is now fully green. Changing the color now also changes the color for the footer.

<img width="1464" alt="Screen Shot 2019-08-13 at 23 29 11" src="https://user-images.githubusercontent.com/5323259/62978749-4b1f0380-be22-11e9-8916-c49c66282450.png">

**Comment by aristath** [comment]
I can't replicate this one

**Comment by paaljoachim** [comment]
I will look into this again another time..

**Comment by carolinan** [comment]
I cannot replicate this one, I do not have to refresh the page to see the background color in the customizer (in Chrome).

When _Override Footer Parts Background_ is not checked, I see a 1px line with the background color at the top.
The background color seem to be visible here because of the default _Border-Top Width_, even when no border color is selected, is this intentional?

**Comment by aristath** [comment]
> The background color seem to be visible here because of the default Border-Top Width, even when no border color is selected, is this intentional?

Yes, that part was intentional. If they have a border-top defined but no color defined then the background color acts as a reasonable fallback 😄

**Comment by aristath** [comment]
Closing this one as I'm still unable to replicate.
@paaljoachim If you can find a consistent way to replicate this issue please reopen it with additional details so we can figure out what's wrong 👍
