### ISSUE TITLE
How to show background image?

### ISSUE THREAD

**Issue by paaljoachim** [wplemon/gridd#97]
Hey

**--- See the next post. ---**

I have installed Gridd on another site that I have.
I added a background image.
Theme Options -> Site Grid. Added Background Image. 
I am not able to see it.
Should there be an option here that overwrites wherever the white background color comes from? 

I turned off the background color option just above the background image option.
I have gone to Content and turned off the Background Color there.

![Screen Shot 2019-08-30 at 13 00 07](https://user-images.githubusercontent.com/5323259/64015998-1ac7ac80-cb26-11e9-93f4-cb8abbbc8d7e.png)

What am I missing?

**Comment by paaljoachim** [comment]
I noticed when changing the site Maximum Width that the background came forth.
I also noticed when adjusting the Theme Options -> Content Background color to no color that nothing happened. I had to also adjust the opacity to zero for the background to shine through.

Removing background color. The latest background color is still seen.
![Screen Shot 2019-08-30 at 13 21 10](https://user-images.githubusercontent.com/5323259/64017122-1a7ce080-cb29-11e9-99a4-d20043c8de68.png)

Bringing the opacity to zero then the background image came through.
![Screen Shot 2019-08-30 at 13 21 19](https://user-images.githubusercontent.com/5323259/64017169-3a140900-cb29-11e9-8f3c-da6fe02c8e44.png)

**Comment by aristath** [comment]
This is perfectly normal.
an empty color is not the same as transparent...
When the value of the variable is empty, the browser will see this CSS: `background-color:;`
That is obviously invalid, so the browser will fallback to the default value - which is white.
Using the transparency is how this should be done.

**Comment by paaljoachim** [comment]
Just remember that all (well many) of the issues that I mention others might also come across. So it would be great to add a note into the docs..:)
